src/Lab5/Lab5/Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Text.RegularExpressions;

namespace Students_Website_lab5_.Models
{
    public class Student
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }

   
       
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("FirstName: " + FirstName);
            sb.Append(" ,LastName: " + LastName);
            sb.Append(", Email: " + Email);
            sb.Append(", PhoneNumber: " + PhoneNumber);

            return sb.ToString();
        }
    }
}

src/Lab5/Lab5/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab5.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

src/Lab5/Lab5/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Students_Website_lab5_.Models;

namespace Students_Website_lab5_.Controllers
{
    public class StudentController : Controller
    {
      
        // GET: Student
        


        public static string fileName = "C:/Students/students.txt";
        public List<Student> students = new List<Student>();
        // GET: Student
        public ActionResult Index()
        {

            return View(readFile(students));
        }
        public static List<Student> readFile(List<Student> students)
        {

            if (!System.IO.File.Exists(fileName))
            {
                System.IO.File.WriteAllText(fileName, null);
            }
            string[] list = System.IO.File.ReadAllLines(fileName);
            students.Clear();
            foreach (string elem in list)
            {
                      string[] fields = elem.Split(',');
                if (elem != "")
                {
                    var student = new Student();
                    student.FirstName = fields[0] ;
                    student.LastName = fields[1];
                    student.Email = fields[2];
                    student.PhoneNumber = fields[3];

             
                   
                    students.Add(student);
                }
            }
            return students;
        }


    }
}

src/Lab5/Lab5/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>This website is a student's platform.</p>

src/Lab5/Lab5/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/Lab5/Lab5/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Students Website</h1>
    <p class="lead">I am Omar Adardour and I am studying in Khpi on the 3th course and my group is : KIT119ia.e.</p>
  
</div>

src/Lab5/Lab5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Student-Website</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Students website", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Students", "Index", "Student")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Students-Website</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

src/Lab5/Lab5/Views/Student/Index.cshtml
@{
    ViewBag.Title = "Students";
}
<div class="studentsPage">
    <h2>Students list</h2>

    </div>
<table class="table text-center table-hover table-striped">
    <thead class="thead-dark">
        <tr style ="background-color:brown;color: white">

            <th style="text-align: center">First Name </th>
            <th style="text-align: center">Last name</th>
            <th style="text-align: center">Email</th>
            <th style="text-align: center">Phone number</th>


        </tr>
    </thead>
    <tbody>
        @{
            int i = 1;
            foreach (var student in @Model)
            {

                <tr class="table-row">

                    <td>@student.FirstName</td>
                    <td>@student.LastName</td>
                    <td>@student.Email</td>
                    <td>@student.PhoneNumber</td>

                </tr>

                i++;
            }
        }


    </tbody>
</table>
    <!-- Modal -->
    